language: python

python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'

script: 
- make install
- make test

deploy:
  provider: pypi
  distributions: sdist
  user: everysense
  password:
    secure: LBwLzScjuo8AM+zLQAJ2qcQ8jVn8292DpIFfFjr5OPA4FQdZK6jrmxlH1PqlA1eqDv8SlljQLVqzzOZWoGAg4BUy6P6NgUf+FZgjNU4jGmjgiWaN2UX+qRgMqogiS+7MO4/otrER90Moj+AZ/N/prvZQL0r7QtGpwOvo8574uWGTS3JP21iHZ1NIbs/PGMTRP3JZgbohcZMplj4/DGgWr+YiGbYnzkxYv9XdGWQ56QOabVmZDvORy43Tmn137Zf/I3M6XUiwn4qgZ6vqCmZg3+hZqxAMNATJ4BGQWafs5kNVJW/Hl6mbNU9X0aMd8Xx4uMqLt1AUMMil6o7IyhifO6T8mr1RZEeuXm7WbsmO6WHrfYKNhketOpJE66u3VPKoLIKaVqwWVoKlen7TjBRHy6z9EifEfxbLDpH6NKqfy5cdhErHUl2+Zy8b4AnAUyCyXp+ouDQu0W3caEg722L8PWP/OzncTpAVK+oIpcmEzeXLNtKvjSOYgZchaegOGH5/wE1WhcyPMPqJJ0EuCQBbUo4krcTRIDNIV3HnGk4bOg9DGqVxj6o1Y+dX/argbUBJbVEzKo7t4qlDxyZ/JLHzNDD88Ef7eyciOHyyQGx59U9xYd5zJp369j/fYSS1M6rakn/0wY7AeKGX7gE6GKudvuve/gbVaB7PzihpNxbCYRA=
  on:
    branch: master
    tags: true
